language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c  'CREATE DATABASE politico_test_db;' -U postgres 

script:
  - pytest --cov=api

after_success:
  - coveralls